config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pages#home"
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  include PgSearch::Model

  include PgSearch::Model
  #multisearchable against: [:title, :synopsis]
  pg_search_scope :search_by_title_and_synopsis,
  against: [ :title, :synopsis ],
  associated_against: {
    director: [ :first_name, :last_name ]
  },
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :synopsis]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
      @movies = Movie.search_by_title_and_synopsis(params[:query])
      #if params[:query].present?
      #  sql_query = <<~SQL
      #    movies.title @@ :query
      #    OR movies.synopsis @@ :query
      #    OR directors.first_name @@ :query
      #    OR directors.last_name @@ :query
      #  SQL
      #  @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
      #else
      #  @movies = Movie.all
      #end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSearch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<%= form_with url: movies_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a movie"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <p><%= movie.synopsis %></p>
          <p><% movie.director.first_name %></p>
          <p><% movie.director.last_name %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>